
server:
  port: 8082

spring:
  datasource:
    username: javaeeBlog
    password: javaeeBlog.*
    url: jdbc:mysql://81.68.205.41:3306/JAVADB?serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    static-path-pattern: /static/**